import assert from 'node:assert/strict'
import test from 'node:test'
import { PAGE1_XML, analyzePagination, buildPage1Body } from '../research/commander-vplus-pagination-metadata-client.mjs'
const xml=(body,attrs='')=>`<x:PLUs xmlns:x="urn:vfi-sapphire:np.domain.2001-07-01"${attrs}>${body}</x:PLUs>`
const fields=['request_succeeded','response_structure_valid','page_field_present','of_pages_field_present','page_source_kind','of_pages_source_kind','page_value_unambiguous','of_pages_value_unambiguous','current_page_is_one','of_pages_bucket','more_pages_present','pagination_metadata_valid','raw_response_retained','product_values_retained','safe_error_code']
const approved=['one','2-5','6-10','11-25','26-50','over-50','unknown']
const valid=(page='1',pages='2')=>analyzePagination(Buffer.from(xml(`<p:page xmlns:p="urn:test">${page}</p:page><p:ofPages xmlns:p="urn:test">${pages}</p:ofPages>`)))
test('fixed request bytes and public node contract are exact',()=>{assert.equal(PAGE1_XML,'<domain:PLUSelect xmlns:domain="urn:vfi-sapphire:np.domain.2001-07-01"><pageSize>100</pageSize><page>1</page></domain:PLUSelect>');assert.equal(buildPage1Body('fixture cookie'),`cmd=vPLUs&cookie=fixture%20cookie\r\n\r\n${PAGE1_XML}`);for(const word of ['query','where','upc','modifier','uPLUs','<page>2</page>'])assert.equal(PAGE1_XML.toLowerCase().includes(word),false);const r=valid('1','913');assert.deepEqual(Object.keys(r),fields);assert.equal(r.safe_error_code,null);assert.equal(r.raw_response_retained,false);assert.equal(r.product_values_retained,false);assert.equal(r.current_page_is_one,true);assert.equal(r.pagination_metadata_valid,true);assert.equal(typeof r.more_pages_present,'boolean');assert.ok(approved.includes(r.of_pages_bucket));assert.equal(JSON.stringify(r).includes('913'),false)})
test('numeric accepted matrix, buckets, element attribute mixed and nested sources',()=>{for(const [n,b]of[[1,'one'],[2,'2-5'],[5,'2-5'],[6,'6-10'],[10,'6-10'],[11,'11-25'],[25,'11-25'],[26,'26-50'],[50,'26-50'],[51,'over-50'],[1000000,'over-50']]){const r=valid('0001',String(n).padStart(4,'0'));assert.equal(r.pagination_metadata_valid,true);assert.equal(r.of_pages_bucket,b)}const attr=analyzePagination(Buffer.from(xml('', ' page="0001" ofPages="000025"')));assert.equal(attr.page_source_kind,'attribute');assert.equal(attr.of_pages_source_kind,'attribute');const mixed=analyzePagination(Buffer.from(xml('<page>01</page>', ' ofPages="002"')));assert.equal(mixed.page_source_kind,'element');assert.equal(mixed.of_pages_source_kind,'attribute');const both=analyzePagination(Buffer.from(xml('<page>1</page><ofPages>02</ofPages>', ' page="01" ofPages="2"')));assert.equal(both.page_source_kind,'mixed');assert.equal(both.of_pages_source_kind,'mixed');assert.equal(both.pagination_metadata_valid,true);const nested=analyzePagination(Buffer.from(xml('<meta><page>1</page><ofPages>2</ofPages></meta>')));assert.equal(nested.pagination_metadata_valid,true)})
test('numeric rejected matrix is safe, unambiguous, and nonleaking',()=>{const cases=['','0','0000','-1','+1','1.0','1e2','abc','1x',' 1','1 ','1 0','1\t','1\n','1000001'];for(const bad of cases){const r=valid(bad,'2');assert.equal(r.pagination_metadata_valid,false,bad);assert.ok(r.safe_error_code);if(bad)assert.equal(JSON.stringify(r).includes(bad),false)}for(const [body,label]of[['<ofPages>2</ofPages>','missing page'],['<page>1</page>','missing ofPages'],['<page>2</page><ofPages>2</ofPages>','page wrong'],['<page>2</page><ofPages>1</ofPages>','order wrong'],['<page>1</page><page>2</page><ofPages>2</ofPages>','page conflict'],['<page>1</page><ofPages>2</ofPages><ofPages>3</ofPages>','pages conflict'],['<page>1</page><ofPages>2</ofPages>','baseline']]){const r=analyzePagination(Buffer.from(xml(body)));if(label==='baseline')assert.equal(r.pagination_metadata_valid,true);else assert.equal(r.pagination_metadata_valid,false,label)}const conflict=analyzePagination(Buffer.from(xml('<page>1</page><ofPages>2</ofPages>',' ofPages="3"')));assert.equal(conflict.of_pages_value_unambiguous,false);assert.equal(conflict.pagination_metadata_valid,false);assert.equal(analyzePagination(Buffer.from(xml(''))).page_source_kind,'none')})
test('xml bounds and output safety reject raw structures',()=>{for(const input of [Buffer.from('<x>'),Buffer.from(xml('<!DOCTYPE x><page>1</page><ofPages>2</ofPages>')),Buffer.from(xml('<!ENTITY x "y"><page>1</page><ofPages>2</ofPages>')),Buffer.from([0xff]),Buffer.alloc(1048577)])assert.throws(()=>analyzePagination(input));const deep=xml('<a>'.repeat(9)+'</a>'.repeat(9));assert.throws(()=>analyzePagination(Buffer.from(deep)));const huge=xml(Array.from({length:5001},()=>'<a/>').join(''));assert.throws(()=>analyzePagination(Buffer.from(huge)));const r=valid('1','999983');const output=JSON.stringify(r);for(const secret of ['999983','<page>','cookie','username','password','certificate','price','description','upc','modifier'])assert.equal(output.toLowerCase().includes(secret.toLowerCase()),false)})
