import assert from 'node:assert/strict'
import { mkdtemp, readFile, rm, writeFile, mkdir } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { spawn } from 'node:child_process'
import test from 'node:test'

const root=path.resolve('connector'),source=path.join(root,'maintenance','run-connector-commander-pagination-metadata.ps1')
const fields=['operation','authentication_succeeded','pagination_request_attempted','pagination_request_succeeded','request_page','request_page_size','query_present','where_present','response_structure_valid','page_field_present','of_pages_field_present','page_source_kind','of_pages_source_kind','page_value_unambiguous','of_pages_value_unambiguous','current_page_is_one','of_pages_bucket','more_pages_present','pagination_metadata_valid','raw_response_retained','product_values_retained','write_attempted','session_disposed','error_code','failure_stage','exception_type']
const childResult={request_succeeded:true,response_structure_valid:true,page_field_present:true,of_pages_field_present:true,page_source_kind:'element',of_pages_source_kind:'element',page_value_unambiguous:true,of_pages_value_unambiguous:true,current_page_is_one:true,of_pages_bucket:'2-5',more_pages_present:true,pagination_metadata_valid:true,raw_response_retained:false,product_values_retained:false,safe_error_code:null}
const run=(file,args=[])=>new Promise(resolve=>{const p=spawn('powershell.exe',['-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',file,...args],{windowsHide:true});let out='',err='';p.stdout.on('data',x=>out+=x);p.stderr.on('data',x=>err+=x);p.on('close',code=>resolve({code,out,err}))})
async function fixture(scenario,{dispose='ok',deadline=30000,child={}}={}){const dir=await mkdtemp(path.join(tmpdir(),'pagination-orchestration-'));const installed=path.join(dir,'installed'),service=path.join(installed,'service'),research=path.join(dir,'research'),maintenance=path.join(dir,'maintenance'),guard=path.join(dir,'guard');await mkdir(service,{recursive:true});await mkdir(research,{recursive:true});await mkdir(maintenance,{recursive:true});await writeFile(path.join(dir,'ca.pem'),'fake')
  await writeFile(path.join(service,'storepulse-machine-config.ps1'),`function Read-StorePulseMachineConfig{param($Path)[pscustomobject]@{commander_install_path='fake';commander_ip='fake'}}`)
  await writeFile(path.join(service,'storepulse-machine-secrets.ps1'),`function Read-StorePulseMachineSecrets{param($Path)[pscustomobject]@{commander_username='fake';commander_password='fake'}}`)
  await writeFile(path.join(service,'storepulse-current-shift-worker.ps1'),`function New-StorePulseCommanderConnection{param($CommanderInstallPath,$CommanderIp,$Username,$Password)${dispose==='null'?'return $null':"$o=[pscustomobject]@{};$o|Add-Member ScriptMethod Dispose {"+(dispose==='throw'?"throw 'UNSAFE_CLEANUP_MESSAGE_913'":'')+"};$o"}};function Get-StorePulseCommanderSessionCookie{param($Connection)'fake-cookie'}`)
  const expectedChild={...childResult,...child},entries=Object.entries(expectedChild);const reordered=scenario==='wrong-order'?entries.reverse():scenario==='adjacent-swap'?[entries[1],entries[0],...entries.slice(2)]:scenario==='first-last-swap'?[entries.at(-1),...entries.slice(1,-1),entries[0]]:scenario==='missing'?entries.slice(0,-1):scenario==='extra'?[...entries,['unexpected_field',false]]:scenario==='renamed'?[['renamed_field',entries[0][1]],...entries.slice(1)]:null
  const payload=scenario==='valid'?JSON.stringify(expectedChild):reordered?JSON.stringify(Object.fromEntries(reordered)):scenario==='stderr'?JSON.stringify(expectedChild):scenario==='invalid-json'?'{not valid json':''
  const childScript=`$null=[Console]::In.ReadToEnd();${scenario==='timeout'?'Start-Sleep -Seconds 2':''}${scenario==='stdout'?'[Console]::Out.Write("X"*9000)':scenario==='stderr'?'[Console]::Error.Write("unsafe-xml-913")':scenario==='nonzero'?"exit 9":`[Console]::Out.Write('${payload.replace(/'/g,"''")}')`}`
  const nodeChild=scenario==='timeout'?'setTimeout(()=>{},2000)':scenario==='stdout'?'process.stdout.write("X".repeat(9000))':scenario==='stderr'?'process.stderr.write("unsafe-xml-913")':scenario==='nonzero'?'process.exit(9)':`process.stdout.write(${JSON.stringify(payload)})`;if(scenario!=='child-missing')await writeFile(path.join(research,'fake-child.mjs'),nodeChild)
  let text=await readFile(source,'utf8');const swaps=[["$installed='C:\\Program Files\\StorePulse\\Connector'",`$installed='${installed.replaceAll('\\','\\\\')}'`],["$node=Join-Path $installed 'runtime\\node\\node.exe'",`$node='${process.execPath.replaceAll('\\','\\\\')}'`],["$ca='C:\\ProgramData\\StorePulse\\certificates\\commander-ca.pem'",`$ca='${path.join(dir,'ca.pem').replaceAll('\\','\\\\')}'`],["$markerRoot='C:\\ProgramData\\StorePulse\\diagnostics\\commander-pagination-metadata'",`$markerRoot='${guard.replaceAll('\\','\\\\')}'`],["research\\commander-vplus-pagination-metadata-client.mjs",'research\\fake-child.mjs']];if(deadline!==30000)swaps.push(['WaitForExit(30000)',`WaitForExit(${deadline})`]);for(const[a,b]of swaps){assert.equal(text.split(a).length-1,1,`anchor ${a}`);text=text.replace(a,b)}const runner=path.join(maintenance,'run.ps1');await writeFile(runner,text);return{dir,runner,guard}}
async function withFixture(scenario,options,fn){const f=await fixture(scenario,options);try{return await fn(f)}finally{await rm(f.dir,{recursive:true,force:true})}}
test('temporary exact-runner copy executes valid, overflow, stderr, nonzero, timeout, and invalid child cases',async()=>{for(const scenario of ['valid','stdout','stderr','nonzero','timeout','empty','invalid-json'])await withFixture(scenario,{deadline:250},async f=>{const r=await run(f.runner);assert.ok(r.out.length<=8192);assert.equal(r.err,'');const body=JSON.parse(r.out);assert.deepEqual(Object.keys(body),fields);assert.equal(body.pagination_request_attempted,true);assert.equal(body.write_attempted,false);assert.equal(body.raw_response_retained,false);assert.equal(body.product_values_retained,false);assert.equal(body.session_disposed,true);if(scenario==='valid')assert.equal(r.code,0,JSON.stringify(body));else{assert.equal(r.code,1);assert.equal(body.pagination_request_succeeded,false);assert.ok(body.error_code);assert.equal(r.out.includes('fake-cookie'),false)}})})
test('runner rejects wrong child field order with a safe public result',async()=>withFixture('wrong-order',{},async f=>{const r=await run(f.runner);const body=JSON.parse(r.out);assert.equal(r.code,1);assert.deepEqual(Object.keys(body),fields);assert.equal(body.pagination_request_attempted,true);assert.equal(body.pagination_request_succeeded,false);assert.equal(body.pagination_metadata_valid,false);assert.equal(body.error_code,'pagination_response_parse');assert.equal(r.err,'')}))
test('runner rejects every malformed child field ordering or shape safely',async()=>{for(const scenario of ['adjacent-swap','first-last-swap','missing','extra','renamed','child-missing'])await withFixture(scenario,{},async f=>{const r=await run(f.runner);const body=JSON.parse(r.out);assert.equal(r.code,1,scenario);assert.deepEqual(Object.keys(body),fields,scenario);assert.equal(body.pagination_request_attempted,true,scenario);assert.equal(body.pagination_request_succeeded,false,scenario);assert.equal(body.pagination_metadata_valid,false,scenario);assert.ok(['pagination_response_parse','pagination_transport_start'].includes(body.error_code),scenario);assert.equal(r.err,'',scenario);assert.equal(r.out.includes('renamed_field'),false,scenario);assert.equal(r.out.includes('unexpected_field'),false,scenario)})})
test('guard repeat and cleanup precedence run through the temporary runner',async()=>withFixture('valid',{dispose:'throw'},async f=>{const first=await run(f.runner);const a=JSON.parse(first.out);assert.equal(first.code,1);assert.equal(a.error_code,'session_dispose_failed');assert.equal(a.failure_stage,'session_dispose');assert.equal(a.session_disposed,false);assert.equal(first.out.includes('UNSAFE_CLEANUP_MESSAGE_913'),false);const second=await run(f.runner);const b=JSON.parse(second.out);assert.equal(second.code,1);assert.equal(b.error_code,'already_attempted');assert.equal(b.pagination_request_attempted,false)}))
test('guard admits exactly one concurrent runner and rejects the loser before authentication',async()=>withFixture('valid',{},async f=>{const [left,right]=await Promise.all([run(f.runner),run(f.runner)]);const results=[left,right].map(r=>({r,body:JSON.parse(r.out)}));assert.equal(results.filter(x=>x.r.code===0).length,1);assert.equal(results.filter(x=>x.body.error_code==='already_attempted').length,1);const loser=results.find(x=>x.body.error_code==='already_attempted').body;assert.equal(loser.authentication_succeeded,false);assert.equal(loser.pagination_request_attempted,false)}))
test('cleanup failure overrides an operation failure without leaking its raw message',async()=>withFixture('empty',{dispose:'throw'},async f=>{const r=await run(f.runner);const body=JSON.parse(r.out);assert.equal(r.code,1);assert.equal(body.error_code,'session_dispose_failed');assert.equal(body.failure_stage,'session_dispose');assert.equal(body.session_disposed,false);assert.equal(r.out.includes('UNSAFE_CLEANUP_MESSAGE_913'),false);assert.equal(r.err,'')}))
test('null cleanup object remains bounded and cannot produce an unsafe public exception',async()=>withFixture('valid',{dispose:'null'},async f=>{const r=await run(f.runner);const body=JSON.parse(r.out);assert.equal(r.code,1);assert.deepEqual(Object.keys(body),fields);assert.equal(body.error_code,'session_dispose_failed');assert.equal(body.failure_stage,'session_dispose');assert.equal(r.err,'')}))
const childCodeStages={invalid_input:'pagination_transport_start',invalid_origin:'pagination_transport_start',ca_file_invalid:'pagination_transport_start',transport_failed:'pagination_transport',timeout:'pagination_transport',response_too_large:'pagination_transport',http_rejected:'pagination_transport',invalid_utf8:'pagination_response_parse',xml_invalid:'pagination_response_parse',xml_unsafe:'pagination_response_parse',structure_limit_exceeded:'pagination_response_parse',pagination_metadata_missing:'pagination_metadata_validate',pagination_metadata_ambiguous:'pagination_metadata_validate',pagination_metadata_invalid:'pagination_metadata_validate',result_too_large:'pagination_response_parse',unexpected_failure:'pagination_response_parse'}
test('runner preserves every approved child safe error with its fixed failure stage',async()=>{for(const [safe_error_code,failure_stage] of Object.entries(childCodeStages))await withFixture('valid',{child:{request_succeeded:false,response_structure_valid:false,pagination_metadata_valid:false,safe_error_code}},async f=>{const r=await run(f.runner),body=JSON.parse(r.out);assert.equal(r.code,1,safe_error_code);assert.deepEqual(Object.keys(body),fields,safe_error_code);assert.equal(body.error_code,safe_error_code);assert.equal(body.failure_stage,failure_stage);assert.equal(body.pagination_request_attempted,true);assert.equal(body.pagination_request_succeeded,false);assert.equal(body.response_structure_valid,false);assert.equal(body.pagination_metadata_valid,false);assert.equal(r.err,'')})})
test('runner preserves independently copied child success, structure, and metadata fields',async()=>withFixture('valid',{child:{request_succeeded:true,response_structure_valid:true,pagination_metadata_valid:false,safe_error_code:'pagination_metadata_missing'}},async f=>{const r=await run(f.runner),body=JSON.parse(r.out);assert.equal(r.code,1);assert.equal(body.pagination_request_succeeded,true);assert.equal(body.response_structure_valid,true);assert.equal(body.pagination_metadata_valid,false);assert.equal(body.error_code,'pagination_metadata_missing');assert.equal(body.failure_stage,'pagination_metadata_validate')}))
test('runner rejects unapproved child safe-error forms without echoing them',async()=>{for(const safe_error_code of ['unknown_child_code','TRANSPORT_FAILED','',7,{},[]])await withFixture('valid',{child:{request_succeeded:false,response_structure_valid:false,pagination_metadata_valid:false,safe_error_code}},async f=>{const r=await run(f.runner),body=JSON.parse(r.out);assert.equal(r.code,1);assert.deepEqual(Object.keys(body),fields);assert.equal(body.error_code,'pagination_response_parse');assert.equal(body.failure_stage,'pagination_response_parse');assert.equal(r.err,'');assert.equal(r.out.includes('unknown_child_code'),false);assert.equal(r.out.includes('TRANSPORT_FAILED'),false)})})
test('null child safe code keeps valid success and uses only generic metadata validation when needed',async()=>{await withFixture('valid',{child:{safe_error_code:null}},async f=>{const r=await run(f.runner),body=JSON.parse(r.out);assert.equal(r.code,0);assert.equal(body.error_code,null);assert.equal(body.failure_stage,null)});await withFixture('valid',{child:{request_succeeded:true,response_structure_valid:true,pagination_metadata_valid:false,safe_error_code:null}},async f=>{const r=await run(f.runner),body=JSON.parse(r.out);assert.equal(r.code,1);assert.equal(body.error_code,'pagination_metadata_invalid');assert.equal(body.failure_stage,'pagination_metadata_validate')})})
