import assert from 'node:assert/strict'
import { spawn } from 'node:child_process'
import { copyFile, mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import path from 'node:path'
import test from 'node:test'
import { fileURLToPath } from 'node:url'
import { createHash } from 'node:crypto'
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'..'),runnerSource=path.join(root,'maintenance','run-connector-commander-page2-probe.ps1'),fixture=path.join(here,'fixtures','commander-page2-probe-orchestration-core')
const fields=['operation','request_page','request_page_size','request_succeeded','bounded_response_received','utf8_valid','xml_parse_succeeded','response_root_valid','representation_analysis_completed','page_two_records_detected','plu_count_bucket','page_target_detected','of_pages_target_detected','page_representation','of_pages_representation','raw_response_retained','product_values_retained','write_attempted','session_disposed','error_code','failure_stage','exception_type']
const hash=async file=>createHash('sha256').update(await readFile(file)).digest('hex').toUpperCase();const ps=s=>s.replaceAll("'","''")
const once=(text,a,b)=>{assert.equal(text.split(a).length-1,1,a);return text.replace(a,b)}
const run=file=>new Promise((resolve,reject)=>{const p=spawn('powershell.exe',['-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',file],{windowsHide:true});let out='',err='';p.stdout.on('data',x=>out+=x);p.stderr.on('data',x=>err+=x);p.on('error',reject);p.on('close',code=>resolve({code,out,err}))})
async function runtime(mode,guard=false){const dir=await mkdtemp(path.join(tmpdir(),'page2-probe-')),maintenance=path.join(dir,'maintenance'),installed=path.join(dir,'installed'),service=path.join(installed,'service'),fx=path.join(dir,'fx'),runner=path.join(maintenance,'run.ps1'),child=path.join(fx,'fake-child.mjs'),guardPath=path.join(dir,'diagnostics','commander-catalog-page2-probe');await mkdir(service,{recursive:true});await mkdir(fx,{recursive:true});await mkdir(maintenance,{recursive:true});await copyFile(runnerSource,runner);await copyFile(path.join(fixture,'fake-child.mjs'),child);await writeFile(path.join(fx,'mode.txt'),mode);const mod=(await readFile(path.join(fixture,'fake-auth.ps1'),'utf8'));for(const n of ['storepulse-machine-config.ps1','storepulse-machine-secrets.ps1','storepulse-current-shift-worker.ps1'])await writeFile(path.join(service,n),mod);let s=await readFile(runner,'utf8');for(const[a,b]of [["$installed='C:\\Program Files\\StorePulse\\Connector'",`$installed='${ps(installed)}'`],["$node=Join-Path $installed 'runtime\\node\\node.exe'",`$node='${ps(process.execPath)}'`],["$child=Join-Path (Split-Path $PSScriptRoot -Parent) 'research\\commander-vplus-page2-probe-child.mjs'",`$child='${ps(child)}'`],["$guard='C:\\ProgramData\\StorePulse\\diagnostics\\commander-catalog-page2-probe'",`$guard='${ps(guardPath)}'`],["$childHash='C6ECC80A6C2E09559A39FE53113FB03CFCE97601C066F1D3E10319B1104D3521'",`$childHash='${await hash(child)}'`],["-Path 'C:\\ProgramData\\StorePulse\\config.json'",`-Path '${ps(path.join(dir,'config.json'))}'`],["-Path 'C:\\ProgramData\\StorePulse\\secrets.json'",`-Path '${ps(path.join(dir,'secrets.json'))}'`]])s=once(s,a,b);await writeFile(runner,s);if(guard){await mkdir(path.dirname(guardPath),{recursive:true});await writeFile(guardPath,'')}return{dir,runner,guardPath}}
async function withRuntime(mode,guard,fn){const r=await runtime(mode,guard);try{await fn(r)}finally{await rm(r.dir,{recursive:true,force:true})}}
function result(x){assert.equal(x.err,'');const body=JSON.parse(x.out);assert.deepEqual(Object.keys(body),fields);assert.equal(body.request_page,2);assert.equal(body.request_page_size,100);assert.equal(body.raw_response_retained,false);assert.equal(body.product_values_retained,false);assert.equal(body.write_attempted,false);return body}
test('temporary runner proves records, zero records, ambiguous analysis, guard refusal, and malformed child safety',async()=>{for(const [mode,guard,check]of [['records',false,b=>{assert.equal(b.page_two_records_detected,true);assert.equal(b.plu_count_bucket,'1-10');assert.equal(b.error_code,null)}],['zero',false,b=>{assert.equal(b.page_two_records_detected,false);assert.equal(b.plu_count_bucket,'0');assert.equal(b.error_code,null)}],['ambiguous',false,b=>{assert.equal(b.page_representation,'ambiguous');assert.equal(b.error_code,null)}],['records',true,b=>{assert.equal(b.error_code,'guard_already_exists');assert.equal(b.failure_stage,'guard_check')}],['invalid',false,b=>{assert.equal(b.error_code,'child_output_invalid');assert.equal(b.failure_stage,'child_output_parse')} ]])await withRuntime(mode,guard,async r=>{const x=await run(r.runner),b=result(x);assert.equal(x.code,b.error_code===null?0:1);assert.equal(b.exception_type,null);assert.equal(b.session_disposed,true);check(b)})})
