-- Repair the create-status reporter's PL/pgSQL output-variable ambiguity.
-- The function returns a column named status, so connector columns must be qualified.

create or replace function public.report_commander_product_create_status(p_connector_id uuid,p_job_id uuid,p_status text,p_verification_upc text,p_verification_modifier text,p_verification_description text,p_verification_department text,p_verification_price numeric,p_verification_payment_product_code text,p_verification_selling_unit text,p_verification_max_qty_per_trans text,p_verification_taxable_rebate text,p_verification_tax_rate_ids text[],p_verification_id_check_ids text[],p_verification_flag_ids text[],p_failure_code text,p_failure_message text)
returns table(job_id uuid,status text) language plpgsql security definer set search_path=pg_catalog,public as $$
declare v_job public.pos_publish_jobs%rowtype; v_store_id uuid; v_now timestamptz:=now(); v_hash text; v_identity public.product_source_identities%rowtype;
begin
 select connector.store_id into v_store_id from public.store_pos_connectors connector where connector.id=p_connector_id and connector.status='active'; if not found then raise exception using errcode='42501',message='connector is not authorized'; end if;
 select * into v_job from public.pos_publish_jobs where id=p_job_id for update; if not found or v_job.store_id<>v_store_id or v_job.assigned_connector_id<>p_connector_id or v_job.claimed_by_connector_id<>p_connector_id or v_job.operation<>'create_product' then raise exception using errcode='42501',message='connector is not authorized'; end if;
 if p_status='sending' and v_job.status='claimed' then update public.pos_publish_jobs set status='sending' where id=v_job.id;
 elsif p_status='verifying' and v_job.status='sending' then update public.pos_publish_jobs set status='verifying' where id=v_job.id;
 elsif p_status='failed' and v_job.status in ('claimed','sending','verifying') then update public.pos_publish_jobs set status='failed',failed_at=v_now,audit_metadata=jsonb_strip_nulls(jsonb_build_object('failure_code',p_failure_code,'completion_note',nullif(p_failure_message,''))) where id=v_job.id;
 elsif p_status='completed' and v_job.status='verifying' and p_verification_upc=v_job.payload->>'upc' and p_verification_modifier=v_job.payload->>'modifier' and p_verification_description=v_job.payload->>'description' and p_verification_department=v_job.payload->>'department' and p_verification_price=v_job.requested_price and p_verification_payment_product_code=v_job.payload->>'payment_product_code' and p_verification_selling_unit=v_job.payload->>'selling_unit' and p_verification_max_qty_per_trans=v_job.payload->>'max_qty_per_trans' and p_verification_taxable_rebate=v_job.payload->>'taxable_rebate' and (select array_agg(value order by value) from jsonb_array_elements_text(v_job.payload->'tax_rate_ids') value) is not distinct from (select array_agg(value order by value) from unnest(p_verification_tax_rate_ids) value) and (select array_agg(value order by value) from jsonb_array_elements_text(v_job.payload->'id_check_ids') value) is not distinct from (select array_agg(value order by value) from unnest(p_verification_id_check_ids) value) and (select array_agg(value order by value) from jsonb_array_elements_text(v_job.payload->'flag_ids') value) is not distinct from (select array_agg(value order by value) from unnest(p_verification_flag_ids) value) then
   select * into v_identity from public.product_source_identities where store_id=v_job.store_id and source_system='commander' and source_product_key=p_verification_upc||'/'||p_verification_modifier for update;
   if found and v_identity.product_id<>v_job.product_id then raise exception using errcode='23514',message='source_identity_conflict'; end if;
   v_hash:=encode(extensions.digest(v_job.payload::text,'sha256'),'hex');
   insert into public.product_source_identities(store_id,product_id,source_system,source_product_key,source_upc,source_modifier,source_payload_hash,metadata,last_matched_at) values(v_job.store_id,v_job.product_id,'commander',p_verification_upc||'/'||p_verification_modifier,p_verification_upc,p_verification_modifier,v_hash,jsonb_build_object('origin','verified_create_product'),v_now) on conflict(store_id,source_system,source_product_key) do update set last_seen_at=v_now,last_matched_at=v_now,updated_at=v_now where public.product_source_identities.product_id=excluded.product_id;
   if not found then null; end if;
   update public.pos_publish_jobs set status='completed',completed_at=v_now,audit_metadata=jsonb_build_object('verification_upc',p_verification_upc,'verification_modifier',p_verification_modifier,'verification_description',p_verification_description,'verification_department',p_verification_department,'verification_price',p_verification_price) where id=v_job.id;
 else raise exception using errcode='23514',message='publishing job completion verification is invalid'; end if;
 return query select v_job.id,p_status;
end; $$;
